[project]
name = "cses"
version = "0.1.0"
description = "Solutions to https://cses.fi/problemset/stats/1068/"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = [
    "mypy>=1.13.0",
    "ruff>=0.8.0",
]
